### ISSUE TITLE
WebAssembly issues

### ISSUE THREAD

**Issue by dwhitney** [Tpt/oxigraph#16]
There were two issues when making this work with WebAssembly

1. UUID - the uuid library [requires](https://docs.rs/uuid/0.8.1/uuid/) that you enable the `wasm-bindgen` (which I'm using) or the `stdweb` features to work with WebAssembly. I'm not sure if I can do this with my own `Cargo.toml` file. It may be possible but I could not figure out how, so I branched master and made the update myself.

2. chrono/time aren't supported in WebAssembly. I had to remove chrono from the application entirely because the `Utc::now` function doesn't work. This was a fairly simple to do because it's only used in two places, but also they are necessary, so some solution is needed instead. When working with dates in WebAssembly, you cause use [js_sys::Date::now](https://docs.rs/js-sys/0.3.28/js_sys/struct.Date.html#method.now).

**Comment by Tpt** [comment]
It's very nice that there are only two issues. i am impressed by the state of Rust libraries with WebAssembly.

It seems possible to make `now` work with Chrono using the `wasmbind` feature: https://github.com/chronotope/chrono/blob/c045750e06b4ea59fa09241eeb585e0bacd0cbb8/src/offset/utc.rs#L49

I believe it's possible to declare dependencies (and their features) conditionally based on the target with something like:
```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }
chrono = { version = "0.8", features = ["wasmbind"] }
wasm-bindgen = "0.2"
js-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
```
